### ISSUE TITLE
Tweet exclusion by retweet/reply

### ISSUE THREAD

**Issue by robhadfield** [badbreze/twitter-posts-to-blog#1]
Hi guys

Plugin is working great and imported Tweets as expected so thanks!

I'm aiming to pull in all tweets by a single user, excluding retweets and replies - is this possible?

Any help appreciated!
Rob

**Comment by robhadfield** [comment]
Here's the search I'm aiming to retrieve : https://twitter.com/search?q=from%3Asumodigitalltd%20-filter%3Areplies&src=typd

**Comment by badbreze** [comment]
use the same syntax on a query string:
from:sumodigitalltd -filter:replies -filter:retweets

for more info:
https://support.twitter.com/articles/71577?lang=en#
https://twitter.com/search-advanced

**Comment by robhadfield** [comment]
Thanks @badbreze, I've been playing with this all day :)

It seems to work with one or the other but not both? I think it might be filtering after the collection of X-amount of tweets? So if all of the last 20 tweets are replies or retweets it gets nothing?

Not sure, will keep trying!
